### PR TITLE
Add requirements.txt

### PR DESCRIPTION
**Pull request by AbhishekSrikanth**
This solves issue #1 
- Added requirements.txt
- Updated README.md

### CODE REVIEW

**Review by kj7rrv — CHANGES_REQUESTED** [review]
discordbridge.py is not supposed to say `pass`. I intentionally omitted it.

**Comment by kj7rrv** [comment]
Other than that it looks good.

**Comment by AbhishekSrikanth** [comment]
Sorry about that. Removed pass from discordsend()

**Comment by kj7rrv** [comment]
Okay, thanks. That function is there for @dkienenb to add code to.

**Pull request merged**
